name: Bug reporting
description: A template you can use to report bugs and/or unexpected behavior.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! This template will help you with creating a report that we can use to understand the bug.

        - This repository is maintained by volunteers, it may take a while for them to come back to you.
        - Remember to include sufficent details and context.
        - If you have mutiple questions, suggestions, or bugs, please submit them in seperate issuses.
        - We accept pull requets. If you know how to fix it - go ahead!

        Please provide the following details about the issue you encountered.  *Issues that do not provide the information requested in this form will be flagged as **incomplete** & automatically closed.*
  - type: markdown
    attributes:
      value: |
        Provide a clear & concise description of the bug.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the observed behavior
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do you reproduce this? Please provide as much step-by-step detail as possible.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen when the reproduce steps are followed?
      placeholder: Tell us what you expected to see!
    validations:
      required: true
